server:
  port: 8000
  error:
    include-stacktrace: NEVER
    include-message: ALWAYS
  servlet:
    context-path: /wishlist/v1
spring:
  cache:
    type: redis
    redis:
      time-to-live: 600000
  application:
    name: Wishlist
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://root:secret@localhost:27017/?authSource=admin}
      database: wishlist
      auto-index-creation: true
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}
wishlist:
  user-max-limit: 20
redis:
  timeout: 2000
  maximumActiveConnectionCount: 100

