version: "3.8"

services:
  api1:
    image: leoferreiralima/wishlist:latest
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 350M

  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
    depends_on:
      - api1
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: 100M
